### PR TITLE
i3lock 2.8 (new formula)

### PR DESCRIPTION
**Pull request by afh**
i3lock is a simple screen locker like slock. After starting it, you will
see a white screen (you can configure the color/an image).
You can return to your screen by entering your password.

### CODE REVIEW

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Passing on this but we may consider it in homebrew/core (as this tap is being moved back there).

**Comment by afh** [comment]
@MikeMcQuaid Ok, thanks for the update. It has become of little importance to me, since I don't care much about homebrew anymore, since it has moved into a direction that I disagree with.

Wishing you much success with the project and thanks for all the effort you and other folks have put into it! 👋  🙂

**Pull request closed without merging**
