### PR TITLE
gtksourceviewmm3 3.18.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
```
hecking for GTKSOURCEVIEWMM... no
configure: error: Package requirements (glibmm-2.4 >= 2.46.1 gtkmm-3.0 >= 3.18.0 gtksourceview-3.0 >= 3.18.0) were not met:

Requested 'glibmm-2.4 >= 2.46.1' but version of glibmm is 2.44.0
You may find new versions of glibmm at http://www.gtkmm.org/
Requested 'gtkmm-3.0 >= 3.18.0' but version of gtkmm is 3.16.0
You may find new versions of gtkmm at http://www.gtkmm.org/

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTKSOURCEVIEWMM_CFLAGS
and GTKSOURCEVIEWMM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

Presume that'll be fixed as we merge more of your PRs in the core.

**Comment by tschoonj** [comment]
That is right indeed

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-x11/commit/2bf303308e933d90fc865734c3a8713b1915b2c8. Thanks Tom!

**Pull request closed without merging**
