### PR TITLE
swi-prolog 7.3.9 (devel) and 7.2.3 (stable)

### PR DESCRIPTION
**Pull request by honnix**
Upgrade swi-prolog to development version 7.3.9 and stable version 7.2.3

### CODE REVIEW

**Comment by dunn** [comment]
Feel like adding a better test while you're at it :smile_cat: ??

**Comment by honnix** [comment]
Thanks for the suggestion.

Yes, that I can do. But not exactly sure what could be better. Because as long as "swipl --version" can execute successfully, the installation should be fine. There is only one dylib depended by swipl binary.

Is there any general guide from Homebrew regarding how/what to test against?

**Comment by dunn** [comment]
We usually try to perform some basic real-life operation; for libraries, we compile a minimal program that uses it; for applications we try to have it perform some common function(s) https://github.com/Homebrew/homebrew/blob/master/Library/Formula/scons.rb#L34-L45

**Comment by honnix** [comment]
OK. I will give it a try. 



Best regards,
Hongxin

**Comment by honnix** [comment]
I added one test case by feeding in a prolog file and asking it to solve a simple goal. How can I trigger the test process?

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-x11/commit/b271cc2c2112909c9ec4196a4c1ab2e41b56753a. Thank you for your contribution to Homebrew @honnix! :smiley_cat:

**Pull request closed without merging**
