### PR TITLE
corrected xlispstat formula

### PR DESCRIPTION
**Pull request by jhbadger**
As discussed, this is the corrected xlispstat formula taken from its own branch and which should be less problematic.

### CODE REVIEW

**Comment by dunn** [comment]
Looking good, one audit failure:
```
==> audit problems
homebrew/x11/xlispstat:
 * Incorrect file permissions (755): chmod 644 /usr/local/Library/Taps/homebrew/homebrew-x11/xlispstat.rb

**Comment by jhbadger** [comment]
Anything remaining to do prior to merge?

**Comment by dunn** [comment]
Oop, sorry for forgetting about this!

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Thanks! Merged as 09f3439355739ce93c032257945dbc441bb5263f.

**Pull request closed without merging**
