### PR TITLE
xdu: desc added

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by apjanke** [comment]
@BrewTestBot test this please.

**Comment by apjanke** [comment]
Installation step is failing in the test bot.

```
failed: brew install ./xdu-3.0.el_capitan.bottle.tar.gz

Stacktrace

        ==> Installing xdu from homebrew/x11
==> Pouring xdu-3.0.el_capitan.bottle.tar.gz
Error: Permission denied - /usr/local/etc/X11/app-defaults/XDu
```

That might be something about how bottles interact with etc files and subdirectories.

Brew `test-bot` breaks locally for me too.

```
$ brew test-bot --keep-logs --junit --local --verbose --skip-homebrew --skip-setup xdu
["--keep-logs", "--junit", "--local", "--verbose", "--skip-homebrew", "--skip-setup", "xdu"]
==> brew uses homebrew/x11/xdu
==> brew fetch --retry homebrew/x11/xdu --build-bottle
==> Fetching xdu from homebrew/x11
==> Downloading https://mirrors.kernel.org/debian/pool/main/x/xdu/xdu_3.0.orig.tar.gz
Downloaded to: /Library/Caches/Homebrew/xdu-3.0.tar.gz
SHA256: 42c018597e31fade56e44b21ed7041f23756532df6e114b5475b4a50cd4df881
Error: No such file or directory - /Users/janke/tmp/test-bot/brewbot/homebrew/x11/xdu-4dbe240/formula.homebrew/x11/xdu.fetch.txt
```

At any rate, there's no bottle available for this formula now, and it installs fine locally for me, so this isn't a regression and can probably be merged.

However...
```
chmod 0555, "XDu.ad"
```
That `0555` is world-writable. Shouldn't it be `0554`?

**Comment by bfontaine** [comment]
Just fixed that `chmod` call; I missed your comment.

**Pull request closed without merging**
