### PR TITLE
gnumeric 1.12.24

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by DomT4** [comment]
```
mkdir: /usr/local/Cellar/goffice/0.10.24/lib/goffice/0.10: Operation not permitted
mkdir: /usr/local/Cellar/goffice/0.10.24/lib/goffice/0.10: No such file or directory
mkdir: /usr/local/Cellar/goffice/0.10.24/lib/goffice/0.10/plugins: No such file or directory
make[2]: *** [install-goffice_gnumericLTLIBRARIES] Error 1
make[2]: *** Waiting for unfinished jobs....
mkdir: /usr/local/Cellar/goffice/0.10.24/lib/goffice/0.10: Operation not permitted
mkdir: /usr/local/Cellar/goffice/0.10.24/lib/goffice/0.10: No such file or directory
mkdir: /usr/local/Cellar/goffice/0.10.24/lib/goffice/0.10/plugins: No such file or directory
make[2]: *** [install-xmlDATA] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
```

Looks like it's trying to break out of the sandbox.

**Comment by tschoonj** [comment]
will fix this during the weekend

**Comment by tschoonj** [comment]
@DomT4 could you pull this one in? Thanks!

**Comment by DomT4** [comment]
Oops, forgot about this. Thanks for the ping. Merged in https://github.com/Homebrew/homebrew-x11/commit/308835841a9efeb60f27b3dfc20af0bb9bd3cb07! :smiley_cat:

**Pull request closed without merging**
