### PR TITLE
zenity 3.14

### PR DESCRIPTION
**Pull request by bfontaine**

### CODE REVIEW

**Comment by bfontaine** [comment]
@mikemcquaid Could you please re-start the build now that Homebrew/homebrew#35626 has been merged? :smiley:

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by bfontaine** [comment]
I removed the test because it starts the X server even when using `-h`/`--help`.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
