### PR TITLE
easy-tag 2.4.0

### PR DESCRIPTION
**Pull request by tschoonj**
version bump

### CODE REVIEW

**Comment by dunn** [comment]
The build failed because it needs to download a patch from MacPorts, which is still having issues.  We'll retry the build when it's back to normal.

**Comment by DomT4** [comment]
There's a build failure on Mountain Lion:

```
/bin/sh: line 1: 81414 Killed: 9               itstool -m "${mo}" ${d}/C/cddb-search.page ${d}/C/file-rename.page ${d}/C/file-select.page ${d}/C/format-specifier.page ${d}/C/image-delete.page ${d}/C/image-export.page ${d}/C/image.page ${d}/C/index.page ${d}/C/introduction.page ${d}/C/keyboard-shortcuts.page ${d}/C/legal.xml ${d}/C/playlist-generate.page ${d}/C/problems-id3.page ${d}/C/problems-ogg-split.page ${d}/C/scanner.page ${d}/C/starting.page ${d}/C/tag-capitalization.page ${d}/C/tag-field.page ${d}/C/tag.page
make[2]: *** [es/es.stamp] Error 137
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [fr/fr.stamp] Error 137
make[2]: *** [el/el.stamp] Error 137
make[2]: *** [hu/hu.stamp] Error 137
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by tschoonj** [comment]
No idea what is causing this. Should I just disable the Mountain Lion build?

**Comment by DomT4** [comment]
It passed on ML this time. Potentially a race condition, there's already a known one in `make install` so perhaps that has worsened.

**Comment by tschoonj** [comment]
Thanks for restarting the build once more then. Shall we leave at this?

**Comment by DomT4** [comment]
Yeah. I'll pull as is. If people report that build failure as more than a one time error we'll probably have to stop it compiling in parallel completely, but we'll see if it gets reported. Merged in https://github.com/Homebrew/homebrew-x11/commit/85a0554400fb3c75fb842e3af940b80a7179d054, Thanks @tschoonj.

**Comment by tschoonj** [comment]
Thanks!

**Comment by robotvert** [comment]
Since updating to this version the unicode support got broken, with easytag telling me to apply [this patch](https://git.gnome.org/browse/easytag/tree/src/tags/id3lib/patch_id3lib_3.8.3_UTF16_writing_bug.diff) to id3lib.
Before it worked with Japanese characters and such, now they're all mangled.

**Comment by tschoonj** [comment]
I updated the id3lib formula with the patch. Can you verify that this works?

**Comment by robotvert** [comment]
@tschoonj confirmed it works when using that version of id3lib.

**Pull request closed without merging**
