### PR TITLE
dwm 6.1

### PR DESCRIPTION
**Pull request by afh**
Please also consider merging #151 when merging this formula, since dwm makes use of dmenu (not has a hard requirement though).

### CODE REVIEW

**Comment by dunn** [comment]
If it's not a hard requirement it can't be used in the test, unfortunately:
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20151110-95113-sk6s9u.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-x11/dwm.rb --verbose
==> /usr/local/Cellar/dwm/6.1/bin/dmenu -v
Error: homebrew/x11/dwm: failed
No such file or directory - /usr/local/Cellar/dwm/6.1/bin/dmenu

**Comment by afh** [comment]
Of course I wanted to test dwm instead of dmenu. I've made the appropriate corrections.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-x11/commit/6e0b15eb47a5fec75169fd7c86f75b8ab0d0ee76. Thanks again!

**Comment by afh** [comment]
Thanks for merging.

**Pull request closed without merging**
