### PR TITLE
libview 0.6.6 (new formula)

### PR DESCRIPTION
**Pull request by vicamo**
Signed-off-by: You-Sheng Yang (楊有勝) <vicamo@gmail.com>

### CODE REVIEW

**Comment by tschoonj** [comment]
This formula is a bit problematic IMHO.

The project appears to be dead as no releases have been made since May 2010. Also I have doubts as to how it could properly work: it has a hard dependency on `:x11` but `gtk+` does not have the x11 backend anymore so I guess that part of the code would never work (and probably lead to segfaults after going quickly going through the source).

@vicamo Can you verify if this package actually works?

@bfontaine FYI

**Comment by vicamo** [comment]
@tschoonj in this package I also install its demo programs, so you can really have a try yourself.

**Comment by tschoonj** [comment]
The tests do not cover the problematic widgets MotionTracker and ToolTip that use the X11 code.

Do you have a project where you use these? From the code it looks like they will result very easily in a segmentation fault.

**Comment by vicamo** [comment]
@tschoonj https://github.com/Homebrew/homebrew/pull/48814 contains an example tool `gvncviewer` that can be configured to use libview. It's not enabled now because libview is not available yet. And, yes, gvncviewer uses only __AutoDrawer__.

**Comment by tschoonj** [comment]
`gtk-vnc` depends on `gtk+3` while `libview` depends on `gtk+` through `gtkmm`. Since you should never mix gtk+2 and gtk+3 code you cannot build `gtk-vnc` with `libview` support.

I suggest you remove the problematic files from `libview/Makefile.in` and just compile without them.

**Comment by MikeMcQuaid** [comment]
Closing due to @tschoonj's comments.

**Pull request closed without merging**
