### PR TITLE
Updated to 15.08 release.

### PR DESCRIPTION
**Pull request by manuseiffel**

### CODE REVIEW

**Comment by dunn** [comment]
Merged in f10c20887f59a9ab440c2d4c1b7d3d129f6639ee, thank you!

**Comment by dmzimmerman** [comment]
Unfortunately this version, like previous versions, does not actually work when built - it triggers assertion failures in gdkimage-quartz.c and the user interface is rendered unusable. See the discussion on https://github.com/Homebrew/homebrew-x11/pull/83

**Comment by dunn** [comment]
Do the command-line tools work?

**Comment by dmzimmerman** [comment]
They appear to; I can definitely build example projects without any issues. However, I was intending to use EiffelStudio on my current project mainly for the visual modeling features, so the user interface was the most important part for me.

**Comment by manuseiffel** [comment]
How do I do to enable the quartz back end to see how we could work around the bug in this back end?

Manu

**Comment by dmzimmerman** [comment]
I'm not sure... I have little experience with building gtk+, I just found the other issue by searching. I think the configure script parameters are in the gtk+.rb file in the main Homebrew repo, and that might be a place to start.

**Comment by dunn** [comment]
It this hasn't been reported upstream, it'd be great if one of you could do that as well.

**Comment by manuseiffel** [comment]
It will take me a few weeks to be able to test this unfortunately. So stay tuned.

 

Manu

**Pull request closed without merging**
