### PR TITLE
curlftpfs: fix head url

### PR DESCRIPTION
**Pull request by ilovezfs**
https://github.com/rfw/curlftpfs.git no longer exists

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 any idea if we have a way to tell CVS to use the password blank?

**Comment by DomT4** [comment]
We can do some [automated](https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/vcodex.rb#L5) passing of "magic words" in formulae, if that works here. Otherwise, not aware of one sadly.

**Comment by ilovezfs** [comment]
@DomT4 In this case it looks like the magic is to make it
`:pserver:anonymous:@curlftpfs.cvs.sourceforge.net:/cvsroot/curlftpfs", :using => :cvs`
instead of
`:pserver:anonymous@curlftpfs.cvs.sourceforge.net:/cvsroot/curlftpfs", :using => :cvs`, which it turns out is how all of our other cvs URLs already are.

**Comment by DomT4** [comment]
Took me a minute to actually spot the difference there! Feel free to 🚢 when you're happy here.

**Pull request closed without merging**
