### PR TITLE
i3 4.10.3

### PR DESCRIPTION
**Pull request by afh**

### CODE REVIEW

**Comment by DomT4** [comment]
Failed to build:

```
[i3-config-wizard] Link i3-config-wizard
Undefined symbols for architecture x86_64:
  "_cairo_xcb_surface_create", referenced from:
      _load_pango_font in libi3.a(font.o)
      _draw_text_pango in libi3.a(font.o)
      _predict_text_width in libi3.a(font.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [i3-config-wizard/i3-config-wizard] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by afh** [comment]
This is due to a limitation of the hombrew cairo formula, since it does not build cairo with xcb support.

See [homebrew issue #42949](https://github.com/Homebrew/homebrew/pull/42949) for details.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-x11/commit/ff0bb78235eaad127b736489c5034d159cbede81. Thanks @afh!

**Pull request closed without merging**
