### PR TITLE
xcb-util-xrm 1.0 (new formula)

### PR DESCRIPTION
**Pull request by afh**
XCB utility functions for the X resource manager

Upcoming version of [i3](https://github.com/Homebrew/homebrew-x11/blob/master/i3.rb) (i.e. the current `next` branch) depend on this.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I vendored this into the i3 PR so it shouldn't be needed: https://github.com/Homebrew/homebrew-x11/pull/268

@afh do you mind testing if #268 works for you?

**Comment by afh** [comment]
@ilovezfs thank you for the work in #268 I just verified that it works very well for me! 👍

**Comment by afh** [comment]
Closing in favour of #268.

**Comment by ilovezfs** [comment]
@afh Thank you for testing that! I will ship it now. (If another formula ends up needing xcb-util-xrm at some point, we can make this a separate formula.)

**Pull request closed without merging**
