### PR TITLE
chezscheme 9.4 (new formula)

### PR DESCRIPTION
**Pull request by VMatrix1900**
Chez Scheme is a compiler and run-time system for the language of the
Revised6 Report on Scheme (R6RS), with numerous extensions. The compiler
generates native code for each target processor, with support for x86,
x86_64, and 32-bit PowerPC architectures.

### CODE REVIEW

**Comment by michaelballantyne** [comment]
@VMatrix1900: I was just about to submit a PR for this but you beat me to it! How would you feel about adding "--threads" and "--installschemename=chez" to the configure and dropping the conflict with MIT Scheme?

I think it would also probably be better to make the X11 dependency optional (per https://github.com/cisco/ChezScheme/issues/9) and put this in the homebrew-core repository, but that would require some hacking on chez's build system.

**Comment by michaelballantyne** [comment]
Or if we wanted to hack it, the formula could comment out the include mentioned in that ticket (`#define LIBX11 "/usr/X11R6/lib/libX11.dylib"`) in `version.h` if the X11 option is off.

**Comment by VMatrix1900** [comment]
@michaelballantyne : Thanks for your suggestion. Upstream may add a configure option to disable the X11 build dependency(cisco/ChezScheme#9). Let's wait for it.

**Comment by MikeMcQuaid** [comment]
@VMatrix1900 Thoughts on that? Want to get this merged or closed, I think.

**Comment by VMatrix1900** [comment]
@MikeMcQuaid  still waiting for the upstream update. But I think it's okay to merge.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
