### PR TITLE
meld 3.14.2

### PR DESCRIPTION
**Pull request by tschoonj**
This one seems to fix the segfault when closing meld: #114

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by DomT4** [comment]
Error here isn't your fault Tom. We're working on it.

**Comment by tschoonj** [comment]
Any changes here?

**Comment by DomT4** [comment]
Working on it still. Couple of things I tried the other night locally caused other problems. It's fairly high on my list.

**Comment by dunn** [comment]
Re #169, can we move this to core?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-x11/commit/43f5c482ad658070b6ad9a73d55d32a0656fbe3b. Thanks again Tom!

Feel free to submit it to the core as desired.

**Comment by tschoonj** [comment]
Shall I instead open one PR for all packages here that depend on gtk2 or gtk3?

**Comment by DomT4** [comment]
Probably best to keep it to a reasonable amount per PR, as they'll be treated like new formula and the CI will kick off about certain bits and pieces I'm sure. 5 or so per PR is probably fine.

**Pull request closed without merging**
