### PR TITLE
i3: remove circular dependency on i3status

### PR DESCRIPTION
**Pull request by dunn**
See Homebrew/homebrew#47915.

### CODE REVIEW

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-x11/commit/ef84174ccef5394416eccd2869130956b48c9409 :wink:

**Comment by dunn** [comment]
D:

**Comment by dunn** [comment]
Why does it say there aren't any merge conflicts, SMH

**Comment by DomT4** [comment]
```
¯\_(ツ)_/¯
```

**Pull request closed without merging**
