### PR TITLE
apply X64 patch for tiger-vnc

### PR DESCRIPTION
**Pull request by Git-Jiro**
Applying patch from issue: https://github.com/Homebrew/homebrew-x11/issues/254

### CODE REVIEW

**Comment by apjanke** [comment]
Looks good, since this is already accepted upstream.

Since it changes the installed binaries, this should include a revision bump to the formula. Could you add a `revision 1` after the main `sha256` line?

**Comment by dunn** [comment]
🔔

**Comment by Git-Jiro** [comment]
Yes, will do!

**Comment by dunn** [comment]
Thanks! Merged as 6df9925d34bdf235f2a233563a2e684adc08d2a1.

**Pull request closed without merging**
