### PR TITLE
revision bumps to use the latest poppler

### PR DESCRIPTION
**Pull request by bfontaine**
Depends on Homebrew/homebrew#37280. (WIP)

* ~~`pdf2svg`~~
* `xournal`
* ~~`inkscape` (doesn’t build, even without poppler, due to a `libiconv` error)~~

### CODE REVIEW

**Comment by bfontaine** [comment]
Inkscape 0.91 doesn’t build, even without poppler, I’m investigating.

**Comment by dunn** [comment]
Got inkscape building in #59; do you want to pull those changes in or test this PR again without inkscape?

**Comment by bfontaine** [comment]
@dunn Sorry for the late response, it might be better to exclude Inkscape from this PR so you can get credit for your work on #59 :wink:

**Comment by dunn** [comment]
Maybe just tack a gimp revision onto here?

**Comment by bfontaine** [comment]
Stuff to check:

- [ ] xournal
- [ ] inkscape
- [ ] gimp

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
Seems like my `brew pull` failed to add an autoclose comment. Fixed in c3f68762.

**Pull request closed without merging**
