### PR TITLE
gxemul 0.6.0.1

### PR DESCRIPTION
**Pull request by dholm**

### CODE REVIEW

**Comment by dholm** [comment]
I have posted the patch to the gxemul-devel mailing list but since I'm not subscribed its awaiting moderation.

**Comment by DomT4** [comment]
Any response upstream on the patch yet?

**Comment by dholm** [comment]
Nothing, but there isn't much activity on the mailing list.

 - http://sourceforge.net/p/gxemul/mailman/message/34513295/

**Comment by DomT4** [comment]
If you add that link above the `patch` line I'll go ahead and merge this.

**Comment by dholm** [comment]
@DomT4 Done!

**Comment by dunn** [comment]
Merged in 3c0c5304d45d4e40697aa7888401b88062301b05, thanks!

**Pull request closed without merging**
