### PR TITLE
Updated to EiffelStudio 15.01

### PR DESCRIPTION
**Pull request by manuseiffel**
I've upgraded the hombrew package to the 15.01 version of EiffelStudio.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks! Mind squashing this down to one commit?

For reference, our preferred commit message format is `formula version`, e.g. `eiffelstudio 15.01`. I can reword it when I merge though, if it's not convenient for you to change.

**Comment by manuseiffel** [comment]
I'm not a git expert so if you could do it that would be best.

**Comment by manuseiffel** [comment]
Is there a reason for this patch not to be merged?

**Comment by manuseiffel** [comment]
Any update?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Test is failing on Mountain Lion:

```
==> brew test --verbose Homebrew/x11/eiffelstudio			 FAILED
Testing eiffelstudio
==> /usr/local/Cellar/eiffelstudio/15.01/studio/spec/macosx-x86-64/bin/ec -version
Failed to execute: /usr/local/Cellar/eiffelstudio/15.01/studio/spec/macosx-x86-64/bin/ec
Error: eiffelstudio: failed
Failed executing: /usr/local/Cellar/eiffelstudio/15.01/studio/spec/macosx-x86-64/bin/ec -version
```

**Comment by manuseiffel** [comment]
Could you get the logs for this failure? I only have Yosemite for testing and it works fine. 

Manu

**Comment by DomT4** [comment]
Afraid not, beside what the test-bot outputs there's no easy way to obtain the build logs, and they're removed fairly quickly from the system to save disk space. I've asked the bot to do a rebuild, because this wasn't an issue when you first submitted the PR so perhaps it was a one time failure.

**Comment by DomT4** [comment]
Same failure on the same platform I'm afraid.

**Comment by mistydemeo** [comment]
It looks like the Mt. Lion install didn't install any files (but still exited 0). The binary package that was built is 833 bytes, as opposed to 86MB in newer OSs.

**Comment by mistydemeo** [comment]
This is the entire output of `compile_exes`:

Sun May 24 18:42:11 +0100 2015

./compile_exes
macosx-x86-64

```
Compile C code of the libraries
"A tout seigneur tout honneur", let's start with the run-time
Compile a commercial run-time
cp: run-time/*.so: No such file or directory
cp: run-time/*.a: No such file or directory
Couldnt generate the run-time
Exiting...
final time:
Sun May 24 18:42:22 2015
```

**Comment by mistydemeo** [comment]
Here's the output of `make_images`:

```
Sun May 24 18:42:22 +0100 2015

./make_images
macosx-x86-64

cp: runtimes/*: No such file or directory
Preparing GPL version
./make_images: line 43: /private/tmp/eiffelstudio20150524-87812-17i6n8g/PorterPackage/Eiffel_15.01/studio/spec/macosx-x86-64/bin/ec: No such file or directory
./make_images: line 44: /private/tmp/eiffelstudio20150524-87812-17i6n8g/PorterPackage/Eiffel_15.01/studio/spec/macosx-x86-64/bin/ecb: No such file or directory
chmod: /private/tmp/eiffelstudio20150524-87812-17i6n8g/PorterPackage/Eiffel_15.01/studio/spec/macosx-x86-64/bin/ec: No such file or directory
chmod: /private/tmp/eiffelstudio20150524-87812-17i6n8g/PorterPackage/Eiffel_15.01/studio/spec/macosx-x86-64/bin/ec: No such file or directory
chmod: /private/tmp/eiffelstudio20150524-87812-17i6n8g/PorterPackage/Eiffel_15.01/studio/spec/macosx-x86-64/bin/ecb: No such file or directory
chmod: /private/tmp/eiffelstudio20150524-87812-17i6n8g/PorterPackage/Eiffel_15.01/studio/spec/macosx-x86-64/bin/ecb: No such file or directory
Building GPL CD image
pax: Unable to access Eiffel_15.01 <No such file or directory>
pax: WARNING! These file names were not selected:
Eiffel_15.01
bzip2: Can't open input file Eiffel_15.01_gpl_96535-macosx-x86-64.tar: No such file or directory.
```

**Comment by mistydemeo** [comment]
Here's the output of `brew gist-logs` - you can see from `01.compile_exes.cc` what it ran.

**Comment by manuseiffel** [comment]
Is this possible to get the content of the file `compile.log’ which is generated when running `compile_exes’? It seems that we maybe using some C compilation flags that do not exist on Mountain Lion.

 

Thanks,

Manu

**Comment by mistydemeo** [comment]
https://gist.github.com/3d9f453a356e2aaca434

```
c++  -pipe -fno-common -fPIC -std=c++11 -c -I.. -I. -I../ipc/app -I./include -I../idrs -O3 -Wall -Wextra -Wno-unused-parameter -pedantic -pipe -fno-common -fPIC -std=c++11 -DEIF_THREADS -DEIF_POSIX_THREADS  scoop/eveqs.cpp -o MTeveqs.o
In file included from scoop/eveqs.cpp:44:
In file included from scoop/processor_registry.hpp:42:
In file included from scoop/processor.hpp:49:
scoop/queue_cache.hpp:53:11: fatal error: 'unordered_map' file not found
#       include <unordered_map>
                ^
```

Is C++11 needed now? If so that'll need to get marked with a `needs :cxx11` dependency, along with an `ENV.cxx11` at the beginning of the install method to ensure the compiler builds in C++11 mode.

**Comment by manuseiffel** [comment]
In this particular release yes. Our forthcoming release 15.05 (in about 1 month away) won’t need C++11.

 

Manu

**Comment by mistydemeo** [comment]
Would you prefer to make a change to the formula to get 15.01 building, or just wait until 15.05?

**Comment by manuseiffel** [comment]
To avoid any issue, I’ll wait for the next release. I’ll provide a new pull request when we are ready.

 

Thanks,

Manu

**Comment by mistydemeo** [comment]
Sounds good, thanks! I'll close this PR.

Where would be the best place for me to report the issue where the buildscript didn't notice that the build had failed?

**Comment by manuseiffel** [comment]
I'll take note of this and try to update our script to fail early. Usually problem reports go either on the http://forum.eiffel.com mailing list for developers of EiffelStudio, or on the bug report page http://support.eiffel.com.

**Comment by mistydemeo** [comment]
Thanks!

**Pull request closed without merging**
