### PR TITLE
jskeus 1.0.13: fix sha256 for force pushed tag

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/euslisp/jskeus/issues/403

### CODE REVIEW

**Comment by dunn** [comment]
From that ticket:

> Maybe the tag is force pushed?

**Comment by wkentaro** [comment]
> Did that turn out to be true?

Yes.

**Comment by dunn** [comment]
Cool, thanks.

**Comment by wkentaro** [comment]
Thanks.

**Pull request closed without merging**
