### PR TITLE
easy-tag 2.2.6

### PR DESCRIPTION
**Pull request by robotvert**
see PR #23 

this new PR simply includes the URL fix from PR #25 so it passes the CI and _hopefully_ gets merged _some day_

(also fix the naming in the commit, the previous PR not respecting the `<name>space<version>` format in the commit message)

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
@xu-cheng If you get a chance, this should be okay to merge. Bot is :+1: on it.

**Comment by xu-cheng** [comment]
En, downstream bottle job fails. Ping @mikemcquaid for fix.

**Comment by DomT4** [comment]
Rats, It did. Didn't spot that. Happening a lot with taps lately, hitting it with Versions as well.

**Comment by mikemcquaid** [comment]
@xu-cheng You're a maintainer now so when these things work I'd be grateful if you could dig in a bit before pinging.

**Comment by mikemcquaid** [comment]
In this case I've kicked off a rebuild. I'm guessing this is due to Jenkins being restarted or something similar.

**Comment by xu-cheng** [comment]
While, I did kick a rebuild for bottle. It didn't work. (More strangly, although I kicked one rebuild, the Homebrew Bottle tasks run multiple times). Also I noticed the bottles were pushed to the bintray. 

So I was not sure how to fix the problem further. Why didn't I think about rebuilding the whole PR? :smirk:

**Comment by mikemcquaid** [comment]
Fair point, thanks @xu-cheng :bow:

**Comment by DomT4** [comment]
> Also I noticed the bottles were pushed to the bintray.

It *didn't* fail on the ` curl ` step? I've had a few weird situations where it says the downstream bottle build has failed but when you check on Bintray the bottles claim to be available for publishing, and the bottles contain the expected contents, but obviously you don't manually publish them because = problems, and the test-bot just repeats its failure on the bottle build. So the bottles get pushed to Bintray, contain the expected contents, but the bot's ` curl ` publish step fails. Everything seems to work except that publish step, It's odd.

**Comment by xu-cheng** [comment]
@mikemcquaid Bottle task is still failing. And somehow it run for 3 times.

**Comment by mikemcquaid** [comment]
@xu-cheng it auto-retried until I just disabled it.

**Comment by mikemcquaid** [comment]
This might help: https://github.com/Homebrew/homebrew/commit/ed239d1a7e9f70904eb03d3725743e104db384fd

**Comment by mikemcquaid** [comment]
(I've retried the job again)

**Comment by xu-cheng** [comment]
It works. Thanks @mikemcquaid .

@robotvert Thanks for the pull request! 🎉

**Pull request closed without merging**
